# Generated by Django 4.0.5 on 2022-10-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220907_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
